// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"imy/internal/dao/model"
)

func newConversationCounter(db *gorm.DB, opts ...gen.DOOption) conversationCounter {
	_conversationCounter := conversationCounter{}

	_conversationCounter.conversationCounterDo.UseDB(db, opts...)
	_conversationCounter.conversationCounterDo.UseModel(&model.ConversationCounter{})

	tableName := _conversationCounter.conversationCounterDo.TableName()
	_conversationCounter.ALL = field.NewAsterisk(tableName)
	_conversationCounter.ConvID = field.NewUint64(tableName, "conv_id")
	_conversationCounter.LatestSeq = field.NewUint64(tableName, "latest_seq")
	_conversationCounter.CreatedAt = field.NewTime(tableName, "created_at")
	_conversationCounter.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversationCounter.DeletedAt = field.NewField(tableName, "deleted_at")

	_conversationCounter.fillFieldMap()

	return _conversationCounter
}

// conversationCounter 会话内序号表
type conversationCounter struct {
	conversationCounterDo conversationCounterDo

	ALL       field.Asterisk
	ConvID    field.Uint64 // 会话id，雪花id
	LatestSeq field.Uint64 // 当前会话最大seq
	CreatedAt field.Time   // 数据插入时间
	UpdatedAt field.Time   // 数据更新时间,最后一次登陆时间
	DeletedAt field.Field  // 删除标记

	fieldMap map[string]field.Expr
}

func (c conversationCounter) Table(newTableName string) *conversationCounter {
	c.conversationCounterDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversationCounter) As(alias string) *conversationCounter {
	c.conversationCounterDo.DO = *(c.conversationCounterDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversationCounter) updateTableName(table string) *conversationCounter {
	c.ALL = field.NewAsterisk(table)
	c.ConvID = field.NewUint64(table, "conv_id")
	c.LatestSeq = field.NewUint64(table, "latest_seq")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *conversationCounter) WithContext(ctx context.Context) *conversationCounterDo {
	return c.conversationCounterDo.WithContext(ctx)
}

func (c conversationCounter) TableName() string { return c.conversationCounterDo.TableName() }

func (c conversationCounter) Alias() string { return c.conversationCounterDo.Alias() }

func (c conversationCounter) Columns(cols ...field.Expr) gen.Columns {
	return c.conversationCounterDo.Columns(cols...)
}

func (c *conversationCounter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversationCounter) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 5)
	c.fieldMap["conv_id"] = c.ConvID
	c.fieldMap["latest_seq"] = c.LatestSeq
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c conversationCounter) clone(db *gorm.DB) conversationCounter {
	c.conversationCounterDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c conversationCounter) replaceDB(db *gorm.DB) conversationCounter {
	c.conversationCounterDo.ReplaceDB(db)
	return c
}

type conversationCounterDo struct{ gen.DO }

func (c conversationCounterDo) Debug() *conversationCounterDo {
	return c.withDO(c.DO.Debug())
}

func (c conversationCounterDo) WithContext(ctx context.Context) *conversationCounterDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversationCounterDo) ReadDB() *conversationCounterDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversationCounterDo) WriteDB() *conversationCounterDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversationCounterDo) Session(config *gorm.Session) *conversationCounterDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversationCounterDo) Clauses(conds ...clause.Expression) *conversationCounterDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversationCounterDo) Returning(value interface{}, columns ...string) *conversationCounterDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversationCounterDo) Not(conds ...gen.Condition) *conversationCounterDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversationCounterDo) Or(conds ...gen.Condition) *conversationCounterDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversationCounterDo) Select(conds ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversationCounterDo) Where(conds ...gen.Condition) *conversationCounterDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversationCounterDo) Order(conds ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversationCounterDo) Distinct(cols ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversationCounterDo) Omit(cols ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversationCounterDo) Join(table schema.Tabler, on ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversationCounterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversationCounterDo) RightJoin(table schema.Tabler, on ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversationCounterDo) Group(cols ...field.Expr) *conversationCounterDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversationCounterDo) Having(conds ...gen.Condition) *conversationCounterDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversationCounterDo) Limit(limit int) *conversationCounterDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversationCounterDo) Offset(offset int) *conversationCounterDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversationCounterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *conversationCounterDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversationCounterDo) Unscoped() *conversationCounterDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversationCounterDo) Create(values ...*model.ConversationCounter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversationCounterDo) CreateInBatches(values []*model.ConversationCounter, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversationCounterDo) Save(values ...*model.ConversationCounter) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversationCounterDo) First() (*model.ConversationCounter, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConversationCounter), nil
	}
}

func (c conversationCounterDo) Take() (*model.ConversationCounter, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConversationCounter), nil
	}
}

func (c conversationCounterDo) Last() (*model.ConversationCounter, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConversationCounter), nil
	}
}

func (c conversationCounterDo) Find() ([]*model.ConversationCounter, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConversationCounter), err
}

func (c conversationCounterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConversationCounter, err error) {
	buf := make([]*model.ConversationCounter, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversationCounterDo) FindInBatches(result *[]*model.ConversationCounter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversationCounterDo) Attrs(attrs ...field.AssignExpr) *conversationCounterDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversationCounterDo) Assign(attrs ...field.AssignExpr) *conversationCounterDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversationCounterDo) Joins(fields ...field.RelationField) *conversationCounterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversationCounterDo) Preload(fields ...field.RelationField) *conversationCounterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversationCounterDo) FirstOrInit() (*model.ConversationCounter, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConversationCounter), nil
	}
}

func (c conversationCounterDo) FirstOrCreate() (*model.ConversationCounter, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConversationCounter), nil
	}
}

func (c conversationCounterDo) FindByPage(offset int, limit int) (result []*model.ConversationCounter, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversationCounterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversationCounterDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversationCounterDo) Delete(models ...*model.ConversationCounter) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversationCounterDo) withDO(do gen.Dao) *conversationCounterDo {
	c.DO = *do.(*gen.DO)
	return c
}
