// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (c *conversation) DB() *gorm.DB {
	return c.conversationDo.DO.UnderlyingDB()
}

func (c *conversation) Get(ctx context.Context, id uint64, withDeleted ...bool) (result *model.Conversation, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversation).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (c *conversation) GetList(ctx context.Context, id []uint64, withDeleted ...bool) (list []*model.Conversation, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversation).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListConversationParams represents the params to list models
type ListConversationParams struct {
	dbgen.Pager

	Type    int8    // optional
	Remark  string  // optional, likely
	PairKey *string // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (c *conversation) List(ctx context.Context, params *ListConversationParams) (list []*model.Conversation, total int64, err error) {
	tx := c.DB().WithContext(ctx).Table(model.TableNameConversation).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Type).IsZero(), "type = ?", params.Type)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Remark).IsZero(), "remark like ?", "%"+params.Remark+"%")).
		Scopes(dbgen.Nullable(params.PairKey != nil, "pair_key = ?", func() any { return *params.PairKey })).
		Order("id desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (c *conversation) Update(ctx context.Context, model *model.Conversation, cols ...string) error {
	return c.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (c *conversation) DeleteByID(ctx context.Context, id uint64) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversation).
		Delete(&model.Conversation{}, id).Error
}

func (c *conversation) Destroy(ctx context.Context, id uint64) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversation).
		Unscoped().
		Delete(&model.Conversation{}, id).Error
}
