// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (c *conversationCounter) DB() *gorm.DB {
	return c.conversationCounterDo.DO.UnderlyingDB()
}

func (c *conversationCounter) Get(ctx context.Context, id uint64, withDeleted ...bool) (result *model.ConversationCounter, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversationCounter).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("conv_id = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (c *conversationCounter) GetList(ctx context.Context, id []uint64, withDeleted ...bool) (list []*model.ConversationCounter, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversationCounter).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("conv_id IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListConversationCounterParams represents the params to list models
type ListConversationCounterParams struct {
	dbgen.Pager

	LatestSeq uint64 // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (c *conversationCounter) List(ctx context.Context, params *ListConversationCounterParams) (list []*model.ConversationCounter, total int64, err error) {
	tx := c.DB().WithContext(ctx).Table(model.TableNameConversationCounter).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.LatestSeq).IsZero(), "latest_seq = ?", params.LatestSeq)).
		Order("conv_id desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (c *conversationCounter) Update(ctx context.Context, model *model.ConversationCounter, cols ...string) error {
	return c.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (c *conversationCounter) DeleteByID(ctx context.Context, id uint64) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversationCounter).
		Delete(&model.ConversationCounter{}, id).Error
}

func (c *conversationCounter) Destroy(ctx context.Context, id uint64) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversationCounter).
		Unscoped().
		Delete(&model.ConversationCounter{}, id).Error
}
