// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (c *conversationMember) DB() *gorm.DB {
	return c.conversationMemberDo.DO.UnderlyingDB()
}

func (c *conversationMember) Get(ctx context.Context, id uint32, withDeleted ...bool) (result *model.ConversationMember, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversationMember).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("user_id = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (c *conversationMember) GetList(ctx context.Context, id []uint32, withDeleted ...bool) (list []*model.ConversationMember, err error) {
	err = c.DB().WithContext(ctx).Table(model.TableNameConversationMember).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("user_id IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListConversationMemberParams represents the params to list models
type ListConversationMemberParams struct {
	dbgen.Pager

	Role        int8   // optional
	LastReadSeq uint64 // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (c *conversationMember) List(ctx context.Context, params *ListConversationMemberParams) (list []*model.ConversationMember, total int64, err error) {
	tx := c.DB().WithContext(ctx).Table(model.TableNameConversationMember).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Role).IsZero(), "role = ?", params.Role)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.LastReadSeq).IsZero(), "last_read_seq = ?", params.LastReadSeq)).
		Order("user_id desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (c *conversationMember) Update(ctx context.Context, model *model.ConversationMember, cols ...string) error {
	return c.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (c *conversationMember) DeleteByID(ctx context.Context, id uint32) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversationMember).
		Delete(&model.ConversationMember{}, id).Error
}

func (c *conversationMember) Destroy(ctx context.Context, id uint32) error {
	return c.DB().WithContext(ctx).Table(model.TableNameConversationMember).
		Unscoped().
		Delete(&model.ConversationMember{}, id).Error
}
