// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (f *friendVerify) DB() *gorm.DB {
	return f.friendVerifyDo.DO.UnderlyingDB()
}

func (f *friendVerify) Get(ctx context.Context, id uint32, withDeleted ...bool) (result *model.FriendVerify, err error) {
	err = f.DB().WithContext(ctx).Table(model.TableNameFriendVerify).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (f *friendVerify) GetList(ctx context.Context, id []uint32, withDeleted ...bool) (list []*model.FriendVerify, err error) {
	err = f.DB().WithContext(ctx).Table(model.TableNameFriendVerify).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListFriendVerifyParams represents the params to list models
type ListFriendVerifyParams struct {
	dbgen.Pager

	SendUuid   string // optional, likely
	RevUuid    string // optional, likely
	SendStatus int8   // optional
	RevStatus  int8   // optional
	Message    string // optional, likely
	Source     int8   // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (f *friendVerify) List(ctx context.Context, params *ListFriendVerifyParams) (list []*model.FriendVerify, total int64, err error) {
	tx := f.DB().WithContext(ctx).Table(model.TableNameFriendVerify).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.SendUuid).IsZero(), "send_uuid like ?", "%"+params.SendUuid+"%")).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.RevUuid).IsZero(), "rev_uuid like ?", "%"+params.RevUuid+"%")).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.SendStatus).IsZero(), "send_status = ?", params.SendStatus)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.RevStatus).IsZero(), "rev_status = ?", params.RevStatus)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Message).IsZero(), "message like ?", "%"+params.Message+"%")).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Source).IsZero(), "source = ?", params.Source)).
		Order("id desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (f *friendVerify) Update(ctx context.Context, model *model.FriendVerify, cols ...string) error {
	return f.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (f *friendVerify) DeleteByID(ctx context.Context, id uint32) error {
	return f.DB().WithContext(ctx).Table(model.TableNameFriendVerify).
		Delete(&model.FriendVerify{}, id).Error
}

func (f *friendVerify) Destroy(ctx context.Context, id uint32) error {
	return f.DB().WithContext(ctx).Table(model.TableNameFriendVerify).
		Unscoped().
		Delete(&model.FriendVerify{}, id).Error
}
