// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"
	"time"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (m *message) DB() *gorm.DB {
	return m.messageDo.DO.UnderlyingDB()
}

func (m *message) Get(ctx context.Context, id uint64, withDeleted ...bool) (result *model.Message, err error) {
	err = m.DB().WithContext(ctx).Table(model.TableNameMessage).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("seq = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (m *message) GetList(ctx context.Context, id []uint64, withDeleted ...bool) (list []*model.Message, err error) {
	err = m.DB().WithContext(ctx).Table(model.TableNameMessage).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("seq IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListMessageParams represents the params to list models
type ListMessageParams struct {
	dbgen.Pager

	MsgId       uint64     // optional
	SendId      uint32     // optional
	Content     string     // optional, likely
	ContentType int8       // optional
	Status      int8       // optional
	RecallId    *uint32    // optional
	RecallAt    *time.Time // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (m *message) List(ctx context.Context, params *ListMessageParams) (list []*model.Message, total int64, err error) {
	tx := m.DB().WithContext(ctx).Table(model.TableNameMessage).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.MsgId).IsZero(), "msg_id = ?", params.MsgId)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.SendId).IsZero(), "send_id = ?", params.SendId)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Content).IsZero(), "content like ?", "%"+params.Content+"%")).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.ContentType).IsZero(), "content_type = ?", params.ContentType)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Status).IsZero(), "status = ?", params.Status)).
		Scopes(dbgen.Nullable(params.RecallId != nil, "recall_id = ?", func() any { return *params.RecallId })).
		Scopes(dbgen.Nullable(params.RecallAt != nil, "recall_at = ?", func() any { return *params.RecallAt })).
		Order("seq desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (m *message) Update(ctx context.Context, model *model.Message, cols ...string) error {
	return m.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (m *message) DeleteByID(ctx context.Context, id uint64) error {
	return m.DB().WithContext(ctx).Table(model.TableNameMessage).
		Delete(&model.Message{}, id).Error
}

func (m *message) Destroy(ctx context.Context, id uint64) error {
	return m.DB().WithContext(ctx).Table(model.TableNameMessage).
		Unscoped().
		Delete(&model.Message{}, id).Error
}
