// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"context"
	"reflect"

	"imy/internal/dao/model"

	"imy/pkg/dbgen"

	"gorm.io/gorm"
)

func (v *verify) DB() *gorm.DB {
	return v.verifyDo.DO.UnderlyingDB()
}

func (v *verify) Get(ctx context.Context, id uint32, withDeleted ...bool) (result *model.Verify, err error) {
	err = v.DB().WithContext(ctx).Table(model.TableNameVerify).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id = ?", id).
		First(&result).
		Error
	if err != nil {
		return nil, err
	}

	return result, nil
}

func (v *verify) GetList(ctx context.Context, id []uint32, withDeleted ...bool) (list []*model.Verify, err error) {
	err = v.DB().WithContext(ctx).Table(model.TableNameVerify).
		Scopes(dbgen.WithDeletedList(withDeleted)).
		Where("id IN ?", id).
		Find(&list).
		Error
	if err != nil {
		return nil, err
	}

	return list, nil
}

// ListVerifyParams represents the params to list models
type ListVerifyParams struct {
	dbgen.Pager

	SendId uint32 // optional
	RevId  uint32 // optional
	Status uint8  // optional

	Deleted bool // optional
}

// List returns the specified models from database by params
func (v *verify) List(ctx context.Context, params *ListVerifyParams) (list []*model.Verify, total int64, err error) {
	tx := v.DB().WithContext(ctx).Table(model.TableNameVerify).
		Scopes(dbgen.WithDeleted(params.Deleted)).
		Scopes(dbgen.Paginate(params.Pager)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.SendId).IsZero(), "send_id = ?", params.SendId)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.RevId).IsZero(), "rev_id = ?", params.RevId)).
		Scopes(dbgen.Cond(!reflect.ValueOf(params.Status).IsZero(), "status = ?", params.Status)).
		Order("id desc")

	total, err = dbgen.FindAndCountTransaction(tx, &list)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

func (v *verify) Update(ctx context.Context, model *model.Verify, cols ...string) error {
	return v.DB().WithContext(ctx).
		Model(model).
		Select(cols).
		Updates(model).
		Error
}

func (v *verify) DeleteByID(ctx context.Context, id uint32) error {
	return v.DB().WithContext(ctx).Table(model.TableNameVerify).
		Delete(&model.Verify{}, id).Error
}

func (v *verify) Destroy(ctx context.Context, id uint32) error {
	return v.DB().WithContext(ctx).Table(model.TableNameVerify).
		Unscoped().
		Delete(&model.Verify{}, id).Error
}
