// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameAuth = "auth"

// Auth 认证表
type Auth struct {
	ID        uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	Account   string                `gorm:"column:account;type:varchar(64);not null;comment:用户账号" json:"account"`                                         // 用户账号
	NickName  string                `gorm:"column:nick_name;type:varchar(64);not null;comment:用户昵称" json:"nick_name"`                                     // 用户昵称
	Password  string                `gorm:"column:password;type:varchar(128);not null;comment:加密后的密码" json:"password"`                                    // 加密后的密码
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName Auth's table name
func (*Auth) TableName() string {
	return TableNameAuth
}
