// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameChatMessage = "chat_message"

// ChatMessage 聊天信息表
type ChatMessage struct {
	ID               uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                          // 主键id
	ConversationID   uint32                `gorm:"column:conversation_id;type:int unsigned;not null;comment:会话id" json:"conversation_id"`                        // 会话id
	SendUUID         string                `gorm:"column:send_uuid;type:varchar(64);not null;comment:发送方uuid" json:"send_uuid"`                                  // 发送方uuid
	ClientMsgID      string                `gorm:"column:client_msg_id;type:varchar(64);not null;comment:客户端幂等ID" json:"client_msg_id"`                          // 客户端幂等ID
	MsgType          int8                  `gorm:"column:msg_type;type:tinyint;not null;default:1;comment:消息类型：1文本、2图片、3语音、4视频、5文件、6系统" json:"msg_type"`         // 消息类型：1文本、2图片、3语音、4视频、5文件、6系统
	Content          string                `gorm:"column:content;type:text;not null;comment:消息内容（文本或JSON）" json:"content"`                                       // 消息内容（文本或JSON）
	ContentExtra     string                `gorm:"column:content_extra;type:varchar(1024);not null;comment:内容扩展（图片宽高、文件大小等）" json:"content_extra"`               // 内容扩展（图片宽高、文件大小等）
	ReplyToMessageID uint64                `gorm:"column:reply_to_message_id;type:bigint unsigned;not null;comment:引用/回复的消息ID" json:"reply_to_message_id"`       // 引用/回复的消息ID
	MentionedUuids   string                `gorm:"column:mentioned_uuids;type:varchar(1024);not null;comment:@用户uuid列表（逗号分隔或JSON）" json:"mentioned_uuids"`       // @用户uuid列表（逗号分隔或JSON）
	IsSystem         bool                  `gorm:"column:is_system;type:tinyint(1);not null;comment:是否系统消息" json:"is_system"`                                    // 是否系统消息
	IsRevoked        bool                  `gorm:"column:is_revoked;type:tinyint(1);not null;comment:是否撤回" json:"is_revoked"`                                    // 是否撤回
	RevokedAt        *time.Time            `gorm:"column:revoked_at;type:datetime;comment:撤回时间" json:"revoked_at"`                                               // 撤回时间
	CreatedAt        time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt        time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt        soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName ChatMessage's table name
func (*ChatMessage) TableName() string {
	return TableNameChatMessage
}
