// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameChatConversation = "chat_conversation"

// ChatConversation 聊天会话表
type ChatConversation struct {
	ID            uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	Type          int8                  `gorm:"column:type;type:tinyint;not null;default:1;comment:会话类型，1表示单聊，2表示群聊" json:"type"`                             // 会话类型，1表示单聊，2表示群聊
	PrivateKey    string                `gorm:"column:private_key;type:varchar(200);not null;comment:会话标识" json:"private_key"`                                // 会话标识
	CreateUUID    string                `gorm:"column:create_uuid;type:varchar(64);not null;comment:创建方" json:"create_uuid"`                                  // 创建方
	Name          string                `gorm:"column:name;type:varchar(128);not null;comment:会话名称,群聊使用,单聊可以为空" json:"name"`                                  // 会话名称,群聊使用,单聊可以为空
	MemberCount   uint32                `gorm:"column:member_count;type:int unsigned;not null;comment:成员数" json:"member_count"`                               // 成员数
	LastMessageID uint64                `gorm:"column:last_message_id;type:bigint unsigned;not null;comment:最后一条消息的id，用于展示" json:"last_message_id"`           // 最后一条消息的id，用于展示
	Avatar        string                `gorm:"column:avatar;type:varchar(512);not null;comment:会话头像（群聊）" json:"avatar"`                                      // 会话头像（群聊）
	Extra         string                `gorm:"column:extra;type:varchar(1024);not null;comment:扩展信息（置顶、公告等）" json:"extra"`                                   // 扩展信息（置顶、公告等）
	CreatedAt     time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt     time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt     soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName ChatConversation's table name
func (*ChatConversation) TableName() string {
	return TableNameChatConversation
}
