// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameChatConversationMember = "chat_conversation_member"

// ChatConversationMember 聊天会话成员表
type ChatConversationMember struct {
	ID                uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	ConversationID    uint32                `gorm:"column:conversation_id;type:int unsigned;not null;comment:会话id" json:"conversation_id"`                        // 会话id
	UserUUID          string                `gorm:"column:user_uuid;type:varchar(64);not null;comment:成员uuid" json:"user_uuid"`                                   // 成员uuid
	Role              int8                  `gorm:"column:role;type:tinyint;not null;default:1;comment:成员角色，1表示普通成员，2表示管理员，群聊使用" json:"role"`                     // 成员角色，1表示普通成员，2表示管理员，群聊使用
	LastReadMessageID uint64                `gorm:"column:last_read_message_id;type:bigint unsigned;not null;comment:最后已读消息ID" json:"last_read_message_id"`       // 最后已读消息ID
	LastReadAt        time.Time             `gorm:"column:last_read_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:最后已读时间" json:"last_read_at"`      // 最后已读时间
	MuteUntil         time.Time             `gorm:"column:mute_until;type:datetime;not null;default:1970-01-01 00:00:00;comment:免打扰截止时间" json:"mute_until"`       // 免打扰截止时间
	IsPinned          bool                  `gorm:"column:is_pinned;type:tinyint(1);not null;comment:是否置顶" json:"is_pinned"`                                      // 是否置顶
	Alias_            string                `gorm:"column:alias;type:varchar(64);not null;comment:群内昵称/备注" json:"alias"`                                          // 群内昵称/备注
	UnreadCount       uint32                `gorm:"column:unread_count;type:int unsigned;not null;comment:未读数（可选缓存字段）" json:"unread_count"`                       // 未读数（可选缓存字段）
	Extra             string                `gorm:"column:extra;type:varchar(512);not null;comment:扩展信息" json:"extra"`                                            // 扩展信息
	CreatedAt         time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt         time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt         soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName ChatConversationMember's table name
func (*ChatConversationMember) TableName() string {
	return TableNameChatConversationMember
}
