// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameConversationMember = "conversation_member"

// ConversationMember 会话成员表
type ConversationMember struct {
	ConvID      uint64                `gorm:"column:conv_id;type:bigint unsigned;primaryKey;comment:会话id，雪花id" json:"conv_id"`                              // 会话id，雪花id
	UserID      uint32                `gorm:"column:user_id;type:int unsigned;primaryKey;comment:用户id" json:"user_id"`                                      // 用户id
	Role        int8                  `gorm:"column:role;type:tinyint;not null;default:1;comment:1-成员，2-管理员" json:"role"`                                   // 1-成员，2-管理员
	LastReadSeq uint64                `gorm:"column:last_read_seq;type:bigint unsigned;not null;comment:最后读到的会话内序号" json:"last_read_seq"`                   // 最后读到的会话内序号
	CreatedAt   time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName ConversationMember's table name
func (*ConversationMember) TableName() string {
	return TableNameConversationMember
}
