// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameConversationCounter = "conversation_counter"

// ConversationCounter 会话内序号表
type ConversationCounter struct {
	ConvID    uint64                `gorm:"column:conv_id;type:bigint unsigned;primaryKey;comment:会话id，雪花id" json:"conv_id"`                              // 会话id，雪花id
	LatestSeq uint64                `gorm:"column:latest_seq;type:bigint unsigned;not null;comment:当前会话最大seq" json:"latest_seq"`                          // 当前会话最大seq
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName ConversationCounter's table name
func (*ConversationCounter) TableName() string {
	return TableNameConversationCounter
}
