// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameConversation = "conversation"

// Conversation 聊天会话表
type Conversation struct {
	ID        uint64                `gorm:"column:id;type:bigint unsigned;primaryKey;comment:会话id，雪花id" json:"id"`                                        // 会话id，雪花id
	Type      int8                  `gorm:"column:type;type:tinyint;not null;default:1;comment:1-单聊,2-群聊" json:"type"`                                    // 1-单聊,2-群聊
	Remark    string                `gorm:"column:remark;type:varchar(128);not null;comment:备注" json:"remark"`                                            // 备注
	PairKey   *string               `gorm:"column:pair_key;type:varchar(32);comment:单聊配对唯一键，群聊为null,解决并发竞争" json:"pair_key"`                              // 单聊配对唯一键，群聊为null,解决并发竞争
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName Conversation's table name
func (*Conversation) TableName() string {
	return TableNameConversation
}
