// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameFriendVerify = "friend_verify"

// FriendVerify 好友验证表
type FriendVerify struct {
	ID         uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	SendUUID   string                `gorm:"column:send_uuid;type:varchar(64);not null;comment:发起方" json:"send_uuid"`                                      // 发起方
	RevUUID    string                `gorm:"column:rev_uuid;type:varchar(64);not null;comment:接收者" json:"rev_uuid"`                                        // 接收者
	SendStatus int8                  `gorm:"column:send_status;type:tinyint;not null;default:1;comment:发送方状态默认1表示待处理，后续还有拒绝，忽略，通过" json:"send_status"`     // 发送方状态默认1表示待处理，后续还有拒绝，忽略，通过
	RevStatus  int8                  `gorm:"column:rev_status;type:tinyint;not null;default:1;comment:接收方状态" json:"rev_status"`                            // 接收方状态
	Message    string                `gorm:"column:message;type:varchar(128);not null;comment:好友验证消息" json:"message"`                                      // 好友验证消息
	Source     int8                  `gorm:"column:source;type:tinyint;not null;default:1;comment:关系来源比如发送方从群聊中获得，还是搜索获得，默认1代表搜索" json:"source"`           // 关系来源比如发送方从群聊中获得，还是搜索获得，默认1代表搜索
	CreatedAt  time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt  time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName FriendVerify's table name
func (*FriendVerify) TableName() string {
	return TableNameFriendVerify
}
