// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameFriend = "friend"

// Friend 好友表
type Friend struct {
	ID         uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	SendUUID   string                `gorm:"column:send_uuid;type:varchar(64);not null;comment:发起方" json:"send_uuid"`                                      // 发起方
	RevUUID    string                `gorm:"column:rev_uuid;type:varchar(64);not null;comment:接收者" json:"rev_uuid"`                                        // 接收者
	SendNotice string                `gorm:"column:send_notice;type:varchar(128);not null;comment:发起方对对方的备注" json:"send_notice"`                           // 发起方对对方的备注
	RevNotice  string                `gorm:"column:rev_notice;type:varchar(128);not null;comment:接收方对对方的备注" json:"rev_notice"`                             // 接收方对对方的备注
	Source     int8                  `gorm:"column:source;type:tinyint;not null;default:1;comment:关系来源比如发送方从群聊中获得，还是搜索获得，默认1代表搜索" json:"source"`           // 关系来源比如发送方从群聊中获得，还是搜索获得，默认1代表搜索
	CreatedAt  time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt  time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt  soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
