// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameMessage = "message"

// Message 聊天消息表
type Message struct {
	ConvID      uint64                `gorm:"column:conv_id;type:bigint unsigned;primaryKey;comment:会话id，雪花id" json:"conv_id"`                              // 会话id，雪花id
	Seq         uint64                `gorm:"column:seq;type:bigint unsigned;primaryKey;comment:会话内序号,严格递增" json:"seq"`                                     // 会话内序号,严格递增
	MsgID       uint64                `gorm:"column:msg_id;type:bigint unsigned;not null;comment:全局消息id，雪花id，客户端重试不会插重复" json:"msg_id"`                     // 全局消息id，雪花id，客户端重试不会插重复
	SendID      uint32                `gorm:"column:send_id;type:int unsigned;not null;comment:发送者id" json:"send_id"`                                       // 发送者id
	Content     string                `gorm:"column:content;type:text;not null;comment:发送内容" json:"content"`                                                // 发送内容
	ContentType int8                  `gorm:"column:content_type;type:tinyint;not null;default:1;comment:1-文本，2-图片，3-文件" json:"content_type"`               // 1-文本，2-图片，3-文件
	Status      int8                  `gorm:"column:status;type:tinyint;not null;default:1;comment:1-正常,2-撤回" json:"status"`                                // 1-正常,2-撤回
	RecallID    *uint32               `gorm:"column:recall_id;type:int unsigned;comment:发送者id" json:"recall_id"`                                            // 发送者id
	RecallAt    *time.Time            `gorm:"column:recall_at;type:datetime;comment:撤回时间" json:"recall_at"`                                                 // 撤回时间
	CreatedAt   time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
