// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID          uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                    // 主键id
	UUID        string                `gorm:"column:uuid;type:varchar(64);not null;comment:用户ID" json:"uuid"`                                      // 用户ID
	NickName    string                `gorm:"column:nick_name;type:varchar(128);not null;comment:用户昵称" json:"nick_name"`                           // 用户昵称
	Password    string                `gorm:"column:password;type:varchar(128);not null;comment:加密后的密码" json:"password"`                           // 加密后的密码
	Email       string                `gorm:"column:email;type:varchar(128);not null;comment:邮箱" json:"email"`                                     // 邮箱
	FileName    string                `gorm:"column:file_name;type:varchar(256);not null;comment:头像文件路径" json:"file_name"`                         // 头像文件路径
	Abstract    string                `gorm:"column:abstract;type:varchar(256);not null;comment:个性签名" json:"abstract"`                             // 个性签名
	Phone       string                `gorm:"column:phone;type:varchar(11);not null;comment:手机号" json:"phone"`                                     // 手机号
	Status      int8                  `gorm:"column:status;type:tinyint;not null;default:1;comment:1表示正常，2表示禁用" json:"status"`                     // 1表示正常，2表示禁用
	Gender      int8                  `gorm:"column:gender;type:tinyint;not null;default:1;comment:1男，2女，3未知" json:"gender"`                       // 1男，2女，3未知
	LastLoginIP string                `gorm:"column:last_login_ip;type:varchar(39);not null;comment:最后一次登陆的ip地址" json:"last_login_ip"`             // 最后一次登陆的ip地址
	Source      int8                  `gorm:"column:source;type:tinyint;not null;default:1;comment:注册来源" json:"source"`                            // 注册来源
	CreatedAt   time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"` // 数据插入时间
	UpdatedAt   time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间" json:"updated_at"` // 数据更新时间
	DeletedAt   soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`           // 删除标记
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
