// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameVerify = "verify"

// Verify 验证表
type Verify struct {
	ID        uint32                `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                             // 主键id
	SendID    uint32                `gorm:"column:send_id;type:int unsigned;not null;comment:发送者id" json:"send_id"`                                       // 发送者id
	RevID     uint32                `gorm:"column:rev_id;type:int unsigned;not null;comment:接受者统称id" json:"rev_id"`                                       // 接受者统称id
	Status    uint8                 `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:处理状态：1待处理，2成功，3失败" json:"status"`               // 处理状态：1待处理，2成功，3失败
	CreatedAt time.Time             `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据插入时间" json:"created_at"`          // 数据插入时间
	UpdatedAt time.Time             `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:数据更新时间,最后一次登陆时间" json:"updated_at"` // 数据更新时间,最后一次登陆时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;type:tinyint(1);not null;comment:删除标记;softDelete:flag" json:"deleted_at"`                    // 删除标记
}

// TableName Verify's table name
func (*Verify) TableName() string {
	return TableNameVerify
}
